<?php

namespace Core\HackingBundle\Repository;

/**
 * CookieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookieRepository extends \Doctrine\ORM\EntityRepository
{
}
